### ISSUE TITLE
Can not build with nng v1.2.4 or v1.2.5

### ISSUE THREAD

**Issue by dsoft-vinhqt** [cwzx/nngpp#13]
The error log:
```
xxxx/libs/nngpp/include/nngpp/stat_view.h: In member function 'nng::stat_view nng::stat_view::find(const char*) const':
xxxx/libs/nngpp/include/nngpp/stat_view.h:86:31: error: 'nng_stat_find' was not declared in this scope
   return nng_stat_find(s, name);
                               ^
xxxx/libs/nngpp/include/nngpp/stat_view.h: In member function 'nng::stat_view nng::stat_view::find(nng::socket_view) const':
xxxx/libs/nngpp/include/nngpp/stat_view.h:90:46: error: 'nng_stat_find_socket' was not declared in this scope
   return nng_stat_find_socket(s, socket.get());
                                              ^
xxxx/libs/nngpp/include/nngpp/stat_view.h: In member function 'nng::stat_view nng::stat_view::find(nng::dialer_view) const':
xxxx/libs/nngpp/include/nngpp/stat_view.h:94:46: error: 'nng_stat_find_dialer' was not declared in this scope
   return nng_stat_find_dialer(s, dialer.get());
                                              ^
xxxx/libs/nngpp/include/nngpp/stat_view.h: In member function 'nng::stat_view nng::stat_view::find(nng::listener_view) const':
xxxx/libs/nngpp/include/nngpp/stat_view.h:98:50: error: 'nng_stat_find_listener' was not declared in this scope
   return nng_stat_find_listener(s, listener.get());
```
Comment out these line can solve the problem, but I think that is not a good idea

**Comment by cwzx** [comment]
For v1.2.4/v1.2.5 use the [nng-v1.2.4 tag of nngpp](https://github.com/cwzx/nngpp/releases).
